import React from 'react'

function LanguageOptions() {
  return (
    <>
      <option value="" disabled>Select language</option>
      {/* <option value="Afrikaans (South Africa)">Afrikaans (South Africa)</option>
      <option value="Albanian (Albania)">Albanian (Albania)</option> */}
      <option value="Arabic (Algeria)">Arabic (Algeria)</option>
      <option value="Arabic (Bahrain)">Arabic (Bahrain)</option>
      <option value="Arabic (Egypt)">Arabic (Egypt)</option>
      <option value="Arabic (Iraq)">Arabic (Iraq)</option>
      <option value="Arabic (Jordan)">Arabic (Jordan)</option>
      <option value="Arabic (Kuwait)">Arabic (Kuwait)</option>
      <option value="Arabic (Lebanon)">Arabic (Lebanon)</option>
      <option value="Arabic (Libya)">Arabic (Libya)</option>
      <option value="Arabic (Morocco)">Arabic (Morocco)</option>
      <option value="Arabic (Oman)">Arabic (Oman)</option>
      <option value="Arabic (Qatar)">Arabic (Qatar)</option>
      <option value="Arabic (Saudi Arabia)">Arabic (Saudi Arabia)</option>
      <option value="Arabic (Syria)">Arabic (Syria)</option>
      <option value="Arabic (Tunisia)">Arabic (Tunisia)</option>
      <option value="Arabic (U. A. E.)">Arabic (U. A. E.)</option>
      <option value="Arabic (Yemen)">Arabic (Yemen)</option>
      {/* <option value="Armenian (Armenia)">Armenian (Armenia)</option>
      <option value="Basque (Spain)">Basque (Spain)</option>
      <option value="Belarusian (Belarus)">Belarusian (Belarus)</option>
      <option value="Bosnian (Bosnia and Herzegovina)">Bosnian (Bosnia and Herzegovina)</option>
      <option value="Bulgarian (Bulgaria)">Bulgarian (Bulgaria)</option>
      <option value="Catalan (Spain)">Catalan (Spain)</option>
      <option value="Chinese Traditional (HK)">Chinese Traditional (HK)</option>
      <option value="Chinese (Macau)">Chinese (Macau)</option>
      <option value="Chinese Simplified">Chinese Simplified</option>
      <option value="Chinese Singapore">Chinese Singapore</option>
      <option value="Chinese Traditional (TW)">Chinese Traditional (TW)</option>
      <option value="Croatian (Bosnia and Herzegovina)">Croatian (Bosnia and Herzegovina)</option>
      <option value="Croatian (Croatia)">Croatian (Croatia)</option>
      <option value="Czech (Czech Republic)">Czech (Czech Republic)</option>
      <option value="Danish (Denmark)">Danish (Denmark)</option>
      <option value="Dutch (Belgium)">Dutch (Belgium)</option>
      <option value="Dutch (Netherlands)">Dutch (Netherlands)</option> */}
      <option value="English (Australia)">English (Australia)</option>
      {/* <option value="English (Belize)">English (Belize)</option> */}
      <option value="English (Canada)">English (Canada)</option>
      {/* <option value="English (Caribbean)">English (Caribbean)</option>
      <option value="English (India)">English (India)</option>
      <option value="English (Ireland)">English (Ireland)</option>
      <option value="English (Jamaica)">English (Jamaica)</option>
      <option value="English (New Zealand)">English (New Zealand)</option>
      <option value="English (Republic of the Philippines)">English (Republic of the Philippines)</option>
      <option value="English (South Africa)">English (South Africa)</option>
      <option value="English (Trinidad and Tobago)">English (Trinidad and Tobago)</option> */}
      <option value="English (United Kingdom)">English (United Kingdom)</option>
      <option value="English (United States)">English (United States)</option>
      {/* <option value="Estonian (Estonia)">Estonian (Estonia)</option>
      <option value="Faroese (Faroe Islands)">Faroese (Faroe Islands)</option>
      <option value="Farsi (Iran)">Farsi (Iran)</option>
      <option value="Finnish (Finland)">Finnish (Finland)</option> */}
      <option value="French (Belgium)">French (Belgium)</option>
      <option value="French (Canada)">French (Canada)</option>
      <option value="French (France)">French (France)</option>
      <option value="French (Luxembourg)">French (Luxembourg)</option>
      <option value="French (Monaco)">French (Monaco)</option>
      <option value="French (Switzerland)">French (Switzerland)</option>
      {/* <option value="Gaelic (Scotland)">Gaelic (Scotland)</option>
      <option value="Galician (Spain)">Galician (Spain)</option>
      <option value="Georgian (Georgia)">Georgian (Georgia)</option> */}
      <option value="German (Austria)">German (Austria)</option>
      <option value="German (Germany)">German (Germany)</option>
      <option value="German (Liechtenstein)">German (Liechtenstein)</option>
      <option value="German (Luxembourg)">German (Luxembourg)</option>
      <option value="German (Switzerland)">German (Switzerland)</option>
      {/* <option value="Greek (Greece)">Greek (Greece)</option>
      <option value="Gujarati (India)">Gujarati (India)</option>
      <option value="Hebrew (Israel)">Hebrew (Israel)</option>
      <option value="Hindi (India)">Hindi (India)</option>
      <option value="Hungarian (Hungary)">Hungarian (Hungary)</option>
      <option value="Indonesian (Indonesia)">Indonesian (Indonesia)</option>
      <option value="Irish">Irish</option> */}
      <option value="Italian (Italy)">Italian (Italy)</option>
      <option value="Italian (Switzerland)">Italian (Switzerland)</option>
      {/* <option value="Japanese (Japan)">Japanese (Japan)</option>
      <option value="Kannada (India)">Kannada (India)</option>
      <option value="Kazakh (Kazakhstan)">Kazakh (Kazakhstan)</option>
      <option value="Konkani (India)">Konkani (India)</option>
      <option value="Korean (Korea)">Korean (Korea)</option>
      <option value="Kyrgyz (Kyrgyzstan)">Kyrgyz (Kyrgyzstan)</option>
      <option value="Latvian (Latvia)">Latvian (Latvia)</option>
      <option value="Lithuanian (Lithuania)">Lithuanian (Lithuania)</option>
      <option value="Macedonian">Macedonian</option>
      <option value="Malay (Malaysia)">Malay (Malaysia)</option>
      <option value="Maltese (Malta)">Maltese (Malta)</option>
      <option value="Maori (New Zealand)">Maori (New Zealand)</option>
      <option value="Marathi (India)">Marathi (India)</option>
      <option value="Mongolian (Mongolia)">Mongolian (Mongolia)</option>
      <option value="Nepali">Nepali</option>
      <option value="Norwegian (Bokmal)">Norwegian (Bokmal)</option>
      <option value="Norwegian (Nynorsk)">Norwegian (Nynorsk)</option>
      <option value="Pashto (Afghanistan)">Pashto (Afghanistan)</option>
      <option value="Polish (Poland)">Polish (Poland)</option>
      <option value="Portuguese (Brazil)">Portuguese (Brazil)</option>
      <option value="Portuguese (Portugal)">Portuguese (Portugal)</option>
      <option value="Punjabi (India)">Punjabi (India)</option>
      <option value="Romanian (Moldova)">Romanian (Moldova)</option>
      <option value="Romanian (Romania)">Romanian (Romania)</option>
      <option value="Russian (Moldova)">Russian (Moldova)</option>
      <option value="Russian (Russia)">Russian (Russia)</option>
      <option value="Sami (Finland)">Sami (Finland)</option>
      <option value="Sami (Norway)">Sami (Norway)</option>
      <option value="Sami (Sweden)">Sami (Sweden)</option>
      <option value="Sanskrit (India)">Sanskrit (India)</option>
      <option value="Serbian (Cyrillic)">Serbian (Cyrillic)</option>
      <option value="Serbian (Latin)">Serbian (Latin)</option>
      <option value="Slovak (Slovakia)">Slovak (Slovakia)</option>
      <option value="Slovenian (Slovenia)">Slovenian (Slovenia)</option> */}
      <option value="Spanish (Argentina)">Spanish (Argentina)</option>
      <option value="Spanish (Bolivia)">Spanish (Bolivia)</option>
      <option value="Spanish (Chile)">Spanish (Chile)</option>
      <option value="Spanish (Colombia)">Spanish (Colombia)</option>
      <option value="Spanish (Costa Rica)">Spanish (Costa Rica)</option>
      <option value="Spanish (Dominican Republic)">Spanish (Dominican Republic)</option>
      <option value="Spanish (Ecuador)">Spanish (Ecuador)</option>
      <option value="Spanish (El Salvador)">Spanish (El Salvador)</option>
      <option value="Spanish (Guatemala)">Spanish (Guatemala)</option>
      <option value="Spanish (Honduras)">Spanish (Honduras)</option>
      <option value="Spanish (Mexico)">Spanish (Mexico)</option>
      <option value="Spanish (Nicaragua)">Spanish (Nicaragua)</option>
      <option value="Spanish (Panama)">Spanish (Panama)</option>
      <option value="Spanish (Paraguay)">Spanish (Paraguay)</option>
      <option value="Spanish (Peru)">Spanish (Peru)</option>
      <option value="Spanish (Puerto Rico)">Spanish (Puerto Rico)</option>
      <option value="Spanish (Spain)">Spanish (Spain)</option>
      <option value="Spanish (Uruguay)">Spanish (Uruguay)</option>
      <option value="Spanish (Venezuela)">Spanish (Venezuela)</option>
      {/* <option value="Swahili (Kenya)">Swahili (Kenya)</option>
      <option value="Swedish (Finland)">Spanish (Finland)</option>
      <option value="Swedish (Sweden)">Spanish (Sweden)</option>
      <option value="Syrian (Syria)">Syrian (Syria)</option>
      <option value="Tagalog (Philippines)">Tagalog (Philippines)</option>
      <option value="Tamil (India)">Tamil (India)</option>
      <option value="Tatar (Russia)">Tatar (Russia)</option>
      <option value="Telugu (India)">Telugu (India)</option>
      <option value="Thai (Thailand)">Thai (Thailand)</option>
      <option value="Tsonga">Tsonga</option>
      <option value="Tswana (South Africa)">Tswana (South Africa)</option>
      <option value="Turkish (Turkey)">Turkish (Turkey)</option>
      <option value="Ukrainian (Turkey)">Ukrainian (Turkey)</option>
      <option value="Urdu (Pakistan)">Urdu (Pakistan)</option>
      <option value="Venda">Tagalog (Philippines)</option>
      <option value="Vietnamese (Vietnam)">Vietnamese (Vietnam)</option>
      <option value="Welsh">Welsh</option>
      <option value="Xhosa (South Africa)">Xhosa (South Africa)</option>
      <option value="Yiddish">Yiddish</option>
      <option value="Zulu (South Africa)">Zulu (South Africa)</option>
      <option value="Khmer (Cambodia)">Khmer (Cambodia)</option>
      <option value="Burmese (Myanmar)">Burmese (Myanmar)</option>
      <option value="English (Singapore)">English (Singapore)</option>
      <option value="Luxembourgish">Luxembourgish</option>
      <option value="Bengali (Bangladesh)">Bengali (Bangladesh)</option>
      <option value="Bengali (India)">Bengali (India)</option>
      <option value="English (U. A. E.)">English (U. A. E.)</option>
      <option value="English (Kenya)">English (Kenya)</option>
      <option value="Assamese (India)">Assamese (India)</option>
      <option value="Oriya (India)">Oriya (India)</option>
      <option value="Amharic (Ethiopia)">Amharic (Ethiopia)</option>
      <option value="Quechua (Peru)">Quechua (Peru)</option>
      <option value="Kurdish">Kurdish</option>
      <option value="Azeri (Latin)">Azeri (Latin)</option>
      <option value="Hausa (Latin)">Hausa (Latin)</option>
      <option value="Igbo">Igbo</option>
      <option value="Lao">Lao</option>
      <option value="Northern Sesotho">Northern Sesotho</option>
      <option value="Persian">Persian</option>
      <option value="Kinyarwanda">Kinyarwanda</option>
      <option value="Sindhi (Pakistan)">Sindhi (Pakistan)</option>
      <option value="Tajik (Tajikistan)">Tajik (Tajikistan)</option>
      <option value="Tigrinya (Ethiopia)">Tigrinya (Ethiopia)</option>
      <option value="Turkmen">Turkmen</option>
      <option value="Setswana (South Africa)">Setswana (South Africa)</option>
      <option value="Hausa">Hausa</option>
      <option value="Welsh (United Kingdom)">Welsh (United Kingdom)</option>
      <option value="Filipino (Philippines)">Filipino (Philippines)</option> */}
      <option value="French (Mauritius)">French (Mauritius)</option>
      <option value="French (Tunisia)">French (Tunisia)</option>
      <option value="French (Morocco)">French (Morocco)</option>
      <option value="French (North Africa)">French (North Africa)</option>
      <option value="French (Senegal)">French (Senegal)</option>
      {/* <option value="Fulani">Fulani</option>
      <option value="Igbo">Igbo</option>
      <option value="Igbo (Nigeria)">Igbo (Nigeria)</option>
      <option value="Nepali (Nepal)">Nepali (Nepal)</option>
      <option value="Somali (Somalia)">Somali (Somalia)</option>
      <option value="English (Nigeria)">English (Nigeria)</option>
      <option value="Swahili (Tanazania)">Swahili (Tanazania)</option> */}
    </>
  )
}

export default LanguageOptions